[versions]
agp = "8.2.2"
kotlin = "1.9.22"
compose = "1.6.3"
composeCompiler = "1.5.11"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
material3Android = "1.1.2"
lifecycleRuntime = "2.7.0"
activityKtx = "1.8.2"
navCompose = "2.7.7"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
